name: Sales Message Scraper

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: sales-message-scraper
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If a lockfile exists, enable npm cache using it
      - name: Setup Node (with npm cache)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Otherwise, set up Node without caching (avoids the error)
      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Cache Puppeteer's browser store (Chromium downloads)
      - name: Cache Puppeteer browser store
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}

      # Prefer ci when lockfile exists, else install
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Run scraper
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        run: npm start
